// Fake property + POI data for the MSC-10368 map UX spike. All names are fictional.
const FAKE_HOTELS = [
  {
    id: "hv-grand",
    letter: "A",
    name: "Harborview Grand",
    brandLabel: "Grand Collection",
    brandColor: "#7c3aed",
    lat: 40.7306,
    lng: -73.9973,
    address: "100 Harbor St, New York, NY",
    phone: "(555) 010-1000",
  },
  {
    id: "cedar-point",
    letter: "B",
    name: "Cedar Point Suites",
    brandLabel: "Suites Collection",
    brandColor: "#0ea5e9",
    lat: 40.7398,
    lng: -73.9903,
    address: "220 Cedar Ave, New York, NY",
    phone: "(555) 010-1001",
  },
];

// A larger POI set covering the full "Points of Interest" filter list, mixing
// points close to the hotels with a few deliberately farther away so the
// radius-based batching (see app.js) has something real to demonstrate.
const FAKE_POIS = [
  {
    id: "poi-accommodation",
    name: "Fictional Extended Stay",
    category: "Accommodation",
    icon: "🛏️",
    color: "#7c3aed",
    lat: 40.732,
    lng: -73.9958,
  },
  {
    id: "poi-bar",
    name: "Fictional Rooftop Lounge",
    category: "Bars / Pubs / Lounges",
    icon: "🍸",
    color: "#db2777",
    lat: 40.7295,
    lng: -73.999,
  },
  {
    id: "poi-coffee",
    name: "Fictional Coffee Co.",
    category: "Coffee & Tea / Cafes",
    icon: "☕",
    color: "#a16207",
    lat: 40.7313,
    lng: -73.999,
  },
  {
    id: "poi-parks",
    name: "Fictional Riverside Park",
    category: "Parks & Recreation Areas",
    icon: "🌳",
    color: "#16a34a",
    lat: 40.7325,
    lng: -73.9985,
  },
  {
    id: "poi-transit",
    name: "Fictional Transit Hub",
    category: "Public Transportation",
    icon: "🚌",
    color: "#0891b2",
    lat: 40.73,
    lng: -73.9955,
  },
  {
    id: "poi-restaurant",
    name: "Fictional Bistro",
    category: "Restaurants",
    icon: "🍴",
    color: "#dc2626",
    lat: 40.729,
    lng: -73.9965,
  },
  {
    id: "poi-snacks",
    name: "Fictional Snack Stop",
    category: "Snacks / Grab-and-Go / Fast Food",
    icon: "🍔",
    color: "#ca8a04",
    lat: 40.7318,
    lng: -73.9995,
  },
  {
    id: "poi-airport",
    name: "Fictional Metro Airport",
    category: "Airports",
    icon: "✈️",
    color: "#334155",
    lat: 40.7455,
    lng: -73.976,
  },
  {
    id: "poi-convention",
    name: "Fictional Expo Center",
    category: "Convention / Exhibition Centers",
    icon: "🎪",
    color: "#ea580c",
    lat: 40.7455,
    lng: -74.005,
  },
  {
    id: "poi-museum",
    name: "Fictional City Museum",
    category: "Museums",
    icon: "🏛️",
    color: "#4338ca",
    lat: 40.7395,
    lng: -73.9887,
  },
  {
    id: "poi-sports",
    name: "Fictional Arena",
    category: "Sports / Entertainment Venues",
    icon: "🏐",
    color: "#be185d",
    lat: 40.718,
    lng: -74.009,
  },
];
