// Fake property + POI data for the MSC-10368 map UX spike. All names are fictional.
const FAKE_HOTELS = [
  {
    id: "hv-grand",
    letter: "A",
    name: "Harborview Grand",
    brandLabel: "Grand Collection",
    brandColor: "#7c3aed",
    lat: 40.7306,
    lng: -73.9973,
    address: "100 Harbor St, New York, NY",
    phone: "(555) 010-1000",
  },
  {
    id: "cedar-point",
    letter: "B",
    name: "Cedar Point Suites",
    brandLabel: "Suites Collection",
    brandColor: "#0ea5e9",
    lat: 40.7398,
    lng: -73.9903,
    address: "220 Cedar Ave, New York, NY",
    phone: "(555) 010-1001",
  },
];

// Mirrors the "Points of Interest" filter categories/icons from the app.
const FAKE_POIS = [
  {
    id: "poi-airport",
    name: "Fictional Metro Airport",
    category: "Airports",
    icon: "✈️",
    color: "#334155",
    lat: 40.7205,
    lng: -74.0045,
  },
  {
    id: "poi-accommodation",
    name: "Fictional Extended Stay",
    category: "Accommodation",
    icon: "🛏️",
    color: "#7c3aed",
    lat: 40.7355,
    lng: -74.0018,
  },
  {
    id: "poi-bar",
    name: "Fictional Rooftop Lounge",
    category: "Bars / Pubs / Lounges",
    icon: "🍸",
    color: "#db2777",
    lat: 40.7268,
    lng: -73.9925,
  },
  {
    id: "poi-coffee",
    name: "Fictional Coffee Co.",
    category: "Coffee & Tea / Cafes",
    icon: "☕",
    color: "#a16207",
    lat: 40.7422,
    lng: -73.9945,
  },
  {
    id: "poi-restaurant",
    name: "Fictional Bistro",
    category: "Restaurants",
    icon: "🍴",
    color: "#dc2626",
    lat: 40.7332,
    lng: -73.9868,
  },
  {
    id: "poi-park",
    name: "Fictional Riverside Park",
    category: "Parks & Recreation Areas",
    icon: "🌳",
    color: "#16a34a",
    lat: 40.7449,
    lng: -73.9998,
  },
];
